/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import negocio.Control;
import negocio.Sesion;

/**
 *
 * @author jorge
 */
public class menu extends javax.swing.JFrame {
    
       private String correoUsuario;
      
       private String rolUsuario;

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }
    
     public menu(String correo) {
        initComponents();
        this.correoUsuario = correo;  // Guardamos el correo en una variable de la clase
      

        configurarBotonesPorRol();  // Configurar visibilidad de botones según el rol
        
   
    }
     
   
   private boolean configurarBotonesPorRol() {
          Control sql = new Control();
       boolean rol = sql.consultarRol(correoUsuario);  // Consultar el saldo en la BD
    if ("1".equals(rol)) {
        btnAdmin.setEnabled(true);  // Habilitar para el administrador
        return true;                // Devuelve true si es administrador
    } else {
        btnAdmin.setEnabled(false);  // Deshabilitar para el usuario estándar
        return false;               // Devuelve false si no es administrador
    }
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel345 = new javax.swing.JLabel();
        btnMisBoletos = new javax.swing.JButton();
        btnEventosD = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnCerrarS = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel345.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel345.setText("Menu");

        btnMisBoletos.setText("Mis boletos");
        btnMisBoletos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisBoletosActionPerformed(evt);
            }
        });

        btnEventosD.setText("Eventos Disponibles");
        btnEventosD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventosDActionPerformed(evt);
            }
        });

        btnSaldo.setText("Saldo");
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnPerfil.setText("Perfil");
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });

        btnCerrarS.setText("Cerrar Sesion");
        btnCerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSActionPerformed(evt);
            }
        });

        btnAdmin.setText("Administrar Eventos");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel345))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnCerrarS, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdmin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEventosD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMisBoletos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSaldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel345, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMisBoletos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEventosD)
                .addGap(18, 18, 18)
                .addComponent(btnSaldo)
                .addGap(18, 18, 18)
                .addComponent(btnPerfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(btnCerrarS)
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        
         perfil p = new perfil();
    p.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
         // Suponiendo que el correo del usuario está almacenado en una variable `correoUsuario`
    

    agregarSaldo saldoPantalla = new agregarSaldo();
    saldoPantalla.setVisible(true);
    this.setVisible(false);  // Cerramos el menú actual

    }//GEN-LAST:event_btnSaldoActionPerformed

    private void btnCerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSActionPerformed
         inicio a = new inicio();
    a.setVisible(true);
    this.setVisible(false);
  
    }//GEN-LAST:event_btnCerrarSActionPerformed

    private void btnMisBoletosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisBoletosActionPerformed
         misBoletos a = new misBoletos();
    a.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnMisBoletosActionPerformed

    private void btnEventosDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventosDActionPerformed
         eventosDisponibles a = new eventosDisponibles();
    a.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnEventosDActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnCerrarS;
    private javax.swing.JButton btnEventosD;
    private javax.swing.JButton btnMisBoletos;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JLabel jLabel345;
    // End of variables declaration//GEN-END:variables
}
